b={ 'BVTK_NT_AdaptiveDataSetSurfaceFilter': [True, True, True, True, True, True, True],
 'BVTK_NT_AdaptiveSubdivisionFilter': [True, True, True, True],
 'BVTK_NT_AggregateDataSetFilter': [True],
 'BVTK_NT_AMRCutPlane': [True, True],
 'BVTK_NT_AMREnzoParticlesReader': [True, True, True, True],
 'BVTK_NT_AMREnzoReader': [True, True, True],
 'BVTK_NT_AMRFlashParticlesReader': [True, True, True],
 'BVTK_NT_AMRFlashReader': [True, True],
 'BVTK_NT_AMRGaussianPulseSource': [True, True, True],
 'BVTK_NT_AMRResampleFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_AMRSliceFilter': [True, True, True, True, True],
 'BVTK_NT_AMRToMultiBlockFilter': [],
 'BVTK_NT_AngularPeriodicFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_AnnotationLayersAlgorithm': [],
 'BVTK_NT_AnnotationLink': [],
 'BVTK_NT_AppendArcLength': [],
 'BVTK_NT_AppendCompositeDataLeaves': [True],
 'BVTK_NT_AppendFilter': [True],
 'BVTK_NT_AppendPoints': [True],
 'BVTK_NT_AppendPolyData': [True, True],
 'BVTK_NT_AppendSelection': [True, True],
 'BVTK_NT_ApplyColors': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ApplyIcons': [True, True, True, True, True, True],
 'BVTK_NT_ArcPlotter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ArcSource': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_AreaContourSpectrumFilter': [True, True, True],
 'BVTK_NT_ArrayCalculator': [True, False, True, False, False, True, False, False, False],
 'BVTK_NT_ArrayDataAlgorithm': [],
 'BVTK_NT_ArrayDataReader': [True, True, True],
 'BVTK_NT_ArrayDataWriter': [True, True, True],
 'BVTK_NT_ArrayReader': [True, True, True],
 'BVTK_NT_ArrayWriter': [True, True, True],
 'BVTK_NT_ArrowSource': [True, True, True, True, True, True],
 'BVTK_NT_AssignAttribute': [],
 'BVTK_NT_AttributeDataToFieldDataFilter': [True],
 'BVTK_NT_AutoCorrelativeStatistics': [True, True, True, True, True, True],
 'BVTK_NT_AVSucdReader': [True, True, True],
 'BVTK_NT_Axes': [True, True, True, True],
 'BVTK_NT_BandedPolyDataContourFilter': [True, True, True, True, True, True],
 'BVTK_NT_BinCellDataFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_BiomTableReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_BivariateLinearTableThreshold': [True, True, True, True, True],
 'BVTK_NT_BlankStructuredGrid': [True, True, True, True, True],
 'BVTK_NT_BlankStructuredGridWithImage': [],
 'BVTK_NT_BlockIdScalars': [],
 'BVTK_NT_BMPReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_BMPWriter': [True, True, True, True, True],
 'BVTK_NT_BooleanOperationPolyDataFilter': [True, True, True],
 'BVTK_NT_BooleanTexture': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_BoundedPointSource': [True, True, True, True, True],
 'BVTK_NT_Box': [True],
 'BVTK_NT_BoxClipDataSet': [True, True, True],
 'BVTK_NT_BrownianPoints': [True, True],
 'BVTK_NT_BSplineTransform': [True, True, True, True],
 'BVTK_NT_ButterflySubdivisionFilter': [True, True],
 'BVTK_NT_BYUReader': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_BYUWriter': [True, True, True, True, True, True, True],
 'BVTK_NT_CastToConcrete': [],
 'BVTK_NT_CellCenters': [True],
 'BVTK_NT_CellDataToPointData': [True, True],
 'BVTK_NT_CellDerivatives': [True, True],
 'BVTK_NT_CellDistanceSelector': [True, True, True],
 'BVTK_NT_CellQuality': [True, True, True],
 'BVTK_NT_CellSizeFilter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_CellTypeSource': [True, True, True, True, True, True],
 'BVTK_NT_ChacoGraphReader': [True],
 'BVTK_NT_ChacoReader': [True, True, True, True, True],
 'BVTK_NT_CheckerboardSplatter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_CleanPolyData': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ClipClosedSurface': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ClipConvexPolyData': [],
 'BVTK_NT_ClipDataSet': [True, True, True, True, True, True],
 'BVTK_NT_ClipPolyData': [True, True, True, True],
 'BVTK_NT_ClipVolume': [True, True, True, True, True, True],
 'BVTK_NT_CMLMoleculeReader': [True],
 'BVTK_NT_CollectGraph': [True, True],
 'BVTK_NT_CollectPolyData': [True],
 'BVTK_NT_CollectTable': [True],
 'BVTK_NT_CompositeCutter': [True, True, True, True],
 'BVTK_NT_CompositeDataGeometryFilter': [],
 'BVTK_NT_CompositeDataProbeFilter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_CompositeDataReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_CompositeDataSetAlgorithm': [],
 'BVTK_NT_CompositeDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ComputeHistogram2DOutliers': [True],
 'BVTK_NT_ComputeQuartiles': [],
 'BVTK_NT_Cone': [True],
 'BVTK_NT_ConeSource': [False, True, True, True, True, True, True],
 'BVTK_NT_ConnectivityFilter': [True, True, True, True, True],
 'BVTK_NT_ContingencyStatistics': [True, True, True, True, True],
 'BVTK_NT_ContourFilter': [True, True, True, True, True, True, True],
 'BVTK_NT_ContourGrid': [True, True, True, True, True],
 'BVTK_NT_ContourLoopExtraction': [True, True, True, True],
 'BVTK_NT_ContourTriangulator': [True],
 'BVTK_NT_ConvertSelection': [True, True, True, True, True],
 'BVTK_NT_ConvertSelectionDomain': [],
 'BVTK_NT_CookieCutter': [],
 'BVTK_NT_CorrelativeStatistics': [True, True, True, True, True],
 'BVTK_NT_CountFaces': [True],
 'BVTK_NT_CountVertices': [True],
 'BVTK_NT_CPExodusIIInSituReader': [True, True],
 'BVTK_NT_CubeSource': [True, True, True, True],
 'BVTK_NT_Cursor2D': [True, True, True, True, True, True, True, True],
 'BVTK_NT_Cursor3D': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_Curvatures': [True, True],
 'BVTK_NT_CutMaterial': [True, True, True, True],
 'BVTK_NT_Cutter': [True, True, True, True],
 'BVTK_NT_Cylinder': [True, True, True],
 'BVTK_NT_CylinderSource': [True, True, True, True, True],
 'BVTK_NT_CylindricalTransform': [True, True],
 'BVTK_NT_DataObjectAlgorithm': [],
 'BVTK_NT_DataObjectGenerator': [True],
 'BVTK_NT_DataObjectReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DataObjectToDataSetFilter': [True, True, True, True, True],
 'BVTK_NT_DataObjectWriter': [True, True, True, True, True],
 'BVTK_NT_DataReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DataSetAlgorithm': [],
 'BVTK_NT_DataSetGradient': [True],
 'BVTK_NT_DataSetGradientPrecompute': [],
 'BVTK_NT_DataSetReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DataSetRegionSurfaceFilter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DataSetSurfaceFilter': [True, True, True, True, True, True, True],
 'BVTK_NT_DataSetToDataObjectFilter': [True, True, True, True, True],
 'BVTK_NT_DataSetTriangleFilter': [True],
 'BVTK_NT_DataSetWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DecimatePolylineFilter': [True],
 'BVTK_NT_DecimatePro': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DeformPointSet': [True],
 'BVTK_NT_Delaunay2D': [True, True, True, True, True],
 'BVTK_NT_Delaunay3D': [True, True, True, True, True, True, True, True],
 'BVTK_NT_DelimitedTextReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DelimitedTextWriter': [True, True, True, True, True],
 'BVTK_NT_DEMReader': [True, True],
 'BVTK_NT_DensifyPointCloudFilter': [True, True, True, True, True, True, True],
 'BVTK_NT_DensifyPolyData': [True],
 'BVTK_NT_DepthImageToPointCloud': [True, True, True, True],
 'BVTK_NT_DepthSortPolyData': [True, True, True, True, True],
 'BVTK_NT_DescriptiveStatistics': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DiagonalMatrixSource': [True, True, True, True, True, True, True],
 'BVTK_NT_DICOMImageReader': [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False],
 'BVTK_NT_DijkstraGraphGeodesicPath': [True, True, True, True, True],
 'BVTK_NT_DijkstraImageGeodesicPath': [True, True, True, True, True, True, True, True],
 'BVTK_NT_DIMACSGraphReader': [True, True, True],
 'BVTK_NT_DIMACSGraphWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_DirectedGraphAlgorithm': [],
 'BVTK_NT_DiscreteMarchingCubes': [True, True, True, True, True],
 'BVTK_NT_DiskSource': [True, True, True, True],
 'BVTK_NT_DistancePolyDataFilter': [True, True, True],
 'BVTK_NT_DuplicatePolyData': [True, True],
 'BVTK_NT_EarthSource': [True, True, True],
 'BVTK_NT_EdgePoints': [True],
 'BVTK_NT_ElevationFilter': [True, True, True],
 'BVTK_NT_EllipseArcSource': [True, True, True, True, True, True, True],
 'BVTK_NT_EllipticalButtonSource': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_EnsembleSource': [True],
 'BVTK_NT_EnSight6BinaryReader': [True, True, True, True, True, True],
 'BVTK_NT_EnSight6Reader': [True, True, True, True, True, True],
 'BVTK_NT_EnSightGoldBinaryReader': [True, True, True, True, True, True],
 'BVTK_NT_EnSightGoldReader': [True, True, True, True, True, True],
 'BVTK_NT_EnSightMasterServerReader': [True, True, True, True, True, True, True],
 'BVTK_NT_EnSightWriter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_EuclideanClusterExtraction': [True, True, True, True, True, True],
 'BVTK_NT_EvenlySpacedStreamlines2D': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ExodusIIReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ExodusIIWriter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ExtractArray': [True],
 'BVTK_NT_ExtractArraysOverTime': [True],
 'BVTK_NT_ExtractBlock': [True, True],
 'BVTK_NT_ExtractCells': [],
 'BVTK_NT_ExtractCTHPart': [True, True, True, True],
 'BVTK_NT_ExtractDataOverTime': [True],
 'BVTK_NT_ExtractDataSets': [],
 'BVTK_NT_ExtractEdges': [],
 'BVTK_NT_ExtractFunctionalBagPlot': [],
 'BVTK_NT_ExtractGeometry': [True, True, True],
 'BVTK_NT_ExtractGrid': [True, True, True],
 'BVTK_NT_ExtractHierarchicalBins': [True, True, True, True],
 'BVTK_NT_ExtractHistogram2D': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ExtractLevel': [],
 'BVTK_NT_ExtractPiece': [],
 'BVTK_NT_ExtractPointCloudPiece': [True],
 'BVTK_NT_ExtractPoints': [True, True, True],
 'BVTK_NT_ExtractPolyDataGeometry': [True, True, True],
 'BVTK_NT_ExtractPolyDataPiece': [True],
 'BVTK_NT_ExtractRectilinearGrid': [True, True, True],
 'BVTK_NT_ExtractSelectedBlock': [True],
 'BVTK_NT_ExtractSelectedFrustum': [True, True, True, True, True],
 'BVTK_NT_ExtractSelectedIds': [True],
 'BVTK_NT_ExtractSelectedLocations': [True],
 'BVTK_NT_ExtractSelectedPolyDataIds': [],
 'BVTK_NT_ExtractSelectedRows': [True],
 'BVTK_NT_ExtractSelectedThresholds': [True],
 'BVTK_NT_ExtractSelection': [True, True, True],
 'BVTK_NT_ExtractSurface': [True, True, True, True],
 'BVTK_NT_ExtractTemporalFieldData': [True],
 'BVTK_NT_ExtractTensorComponents': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ExtractTimeSteps': [True, True, True, True],
 'BVTK_NT_ExtractUnstructuredGrid': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ExtractUnstructuredGridPiece': [True],
 'BVTK_NT_ExtractUserDefinedPiece': [True],
 'BVTK_NT_ExtractVectorComponents': [True],
 'BVTK_NT_ExtractVOI': [True, True, True],
 'BVTK_NT_FacetReader': [True],
 'BVTK_NT_FacetWriter': [True],
 'BVTK_NT_FastSplatter': [True, True, True, True, True],
 'BVTK_NT_FeatureEdges': [True, True, True, True, True, True],
 'BVTK_NT_FiberSurface': [],
 'BVTK_NT_FieldDataToAttributeDataFilter': [True, True, True],
 'BVTK_NT_FillHolesFilter': [True],
 'BVTK_NT_FitImplicitFunction': [True, True, True],
 'BVTK_NT_FixedWidthTextReader': [True, True, True, True],
 'BVTK_NT_FLUENTReader': [True, True],
 'BVTK_NT_FlyingEdges2D': [True, True, True],
 'BVTK_NT_FlyingEdges3D': [True, True, True, True, True, True],
 'BVTK_NT_FlyingEdgesPlaneCutter': [True, True, True],
 'BVTK_NT_ForceTime': [True, True],
 'BVTK_NT_FrustumSource': [True, True],
 'BVTK_NT_GAMBITReader': [True],
 'BVTK_NT_GaussianCubeReader': [True, True, True],
 'BVTK_NT_GaussianCubeReader2': [True],
 'BVTK_NT_GaussianSplatter': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GeneralTransform': [],
 'BVTK_NT_GenericClip': [True, True, True, True, True],
 'BVTK_NT_GenericContourFilter': [True, True, True, True],
 'BVTK_NT_GenericCutter': [True, True],
 'BVTK_NT_GenericDataObjectReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GenericDataObjectWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GenericDataSetTessellator': [True, True],
 'BVTK_NT_GenericEnSightReader': [True, True, True, True, True, True],
 'BVTK_NT_GenericGeometryFilter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GenericGlyph3DFilter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GenericOutlineFilter': [],
 'BVTK_NT_GenericProbeFilter': [],
 'BVTK_NT_GenericStreamTracer': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GeometryFilter': [False, False, False, False, False, False, False, False, False],
 'BVTK_NT_GESignaReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_Glyph2D': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_Glyph3D': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GlyphSource2D': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GradientFilter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GraphAlgorithm': [],
 'BVTK_NT_GraphAnnotationLayersFilter': [],
 'BVTK_NT_GraphLayoutFilter': [True, True, True, True, True],
 'BVTK_NT_GraphReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GraphToGlyphs': [True, True, True, True],
 'BVTK_NT_GraphToPoints': [],
 'BVTK_NT_GraphToPolyData': [True, True],
 'BVTK_NT_GraphWeightEuclideanDistanceFilter': [],
 'BVTK_NT_GraphWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_GreedyTerrainDecimation': [True, True, True, True, True, True, True],
 'BVTK_NT_GridSynchronizedTemplates3D': [True, True, True, True, True],
 'BVTK_NT_GridTransform': [True, True, True, True, True],
 'BVTK_NT_HedgeHog': [True, True],
 'BVTK_NT_HierarchicalBinningFilter': [True, True, True, True],
 'BVTK_NT_HierarchicalBoxDataSetAlgorithm': [],
 'BVTK_NT_HierarchicalDataExtractDataSets': [],
 'BVTK_NT_HierarchicalDataExtractLevel': [],
 'BVTK_NT_HierarchicalDataLevelFilter': [],
 'BVTK_NT_HierarchicalDataSetGeometryFilter': [],
 'BVTK_NT_HighestDensityRegionsStatistics': [True, True, True, True, True],
 'BVTK_NT_HoudiniPolyDataWriter': [True],
 'BVTK_NT_Hull': [],
 'BVTK_NT_HyperStreamline': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_HyperTreeGridAxisClip': [True, True, True, True, True],
 'BVTK_NT_HyperTreeGridAxisCut': [True, True],
 'BVTK_NT_HyperTreeGridAxisReflection': [True, True],
 'BVTK_NT_HyperTreeGridCellCenters': [True],
 'BVTK_NT_HyperTreeGridContour': [True],
 'BVTK_NT_HyperTreeGridDepthLimiter': [True],
 'BVTK_NT_HyperTreeGridGeometry': [],
 'BVTK_NT_HyperTreeGridPlaneCutter': [True, True],
 'BVTK_NT_HyperTreeGridSource': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_HyperTreeGridThreshold': [True, True],
 'BVTK_NT_HyperTreeGridToUnstructuredGrid': [],
 'BVTK_NT_IconGlyphFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_IdentityTransform': [],
 'BVTK_NT_IdFilter': [True, True, True, True],
 'BVTK_NT_ImageAccumulate': [True, True, True, True, True],
 'BVTK_NT_ImageAnisotropicDiffusion2D': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageAnisotropicDiffusion3D': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageAppend': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageAppendComponents': [True, True, True, True, True, True],
 'BVTK_NT_ImageBlend': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageBSplineCoefficients': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageButterworthHighPass': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageButterworthLowPass': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageCacheFilter': [True],
 'BVTK_NT_ImageCanvasSource2D': [True, True, True, True, True],
 'BVTK_NT_ImageCast': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageChangeInformation': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageCheckerboard': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageCityBlockDistance': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageClip': [True, True],
 'BVTK_NT_ImageConnectivityFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageConstantPad': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageContinuousDilate3D': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageContinuousErode3D': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageConvolve': [True, True, True, True, True, True],
 'BVTK_NT_ImageCorrelation': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageCursor3D': [True, True, True],
 'BVTK_NT_ImageDataGeometryFilter': [False, False, False],
 'BVTK_NT_ImageDataStreamer': [True],
 'BVTK_NT_ImageDataToPointSet': [],
 'BVTK_NT_ImageDataToUniformGrid': [True],
 'BVTK_NT_ImageDifference': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageDilateErode3D': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageDivergence': [True, True, True, True, True, True],
 'BVTK_NT_ImageDotProduct': [True, True, True, True, True, True],
 'BVTK_NT_ImageEllipsoidSource': [True, True, True, True, True],
 'BVTK_NT_ImageEuclideanDistance': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageEuclideanToPolar': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageExtractComponents': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageFFT': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageFourierCenter': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageGaussianSmooth': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageGaussianSource': [True, True, True],
 'BVTK_NT_ImageGradient': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageGradientMagnitude': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageGridSource': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageHistogram': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageHistogramStatistics': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageHSIToRGB': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageHSVToRGB': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageHybridMedian2D': [True, True, True, True, True, True],
 'BVTK_NT_ImageIdealHighPass': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageIdealLowPass': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageImport': [True, True, True, True, True],
 'BVTK_NT_ImageIslandRemoval2D': [True, True, True, True],
 'BVTK_NT_ImageLaplacian': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageLogarithmicScale': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageLogic': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageLuminance': [True, True, True, True, True, True],
 'BVTK_NT_ImageMagnify': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMagnitude': [True, True, True, True, True, True],
 'BVTK_NT_ImageMandelbrotSource': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageMapToColors': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMapToRGBA': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMapToWindowLevelColors': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMarchingCubes': [True, True, True, True, True],
 'BVTK_NT_ImageMask': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMaskBits': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMathematics': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageMedian3D': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageMirrorPad': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageNoiseSource': [True, True],
 'BVTK_NT_ImageNonMaximumSuppression': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageNormalize': [True, True, True, True, True, True],
 'BVTK_NT_ImageOpenClose3D': [True, True],
 'BVTK_NT_ImagePadFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImagePermute': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageQuantizeRGBToIndex': [True, True, True, True, True, True],
 'BVTK_NT_ImageRange3D': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageReader2': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageRectilinearWipe': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageResample': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageResize': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageReslice': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageResliceToColors': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageRFFT': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageRGBToHSI': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageRGBToHSV': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageRGBToYIQ': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageSeedConnectivity': [True, True, True, True],
 'BVTK_NT_ImageSeparableConvolution': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageShiftScale': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageShrink3D': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageSinusoidSource': [True, True, True, True],
 'BVTK_NT_ImageSkeleton2D': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageSlab': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageSobel2D': [True, True, True, True, True, True],
 'BVTK_NT_ImageSobel3D': [True, True, True, True, True, True],
 'BVTK_NT_ImageSpatialAlgorithm': [True, True, True, True, True, True],
 'BVTK_NT_ImageStencil': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageStencilAlgorithm': [],
 'BVTK_NT_ImageStencilSource': [True, True, True],
 'BVTK_NT_ImageStencilToImage': [True, True, True],
 'BVTK_NT_ImageThreshold': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageThresholdConnectivity': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageToAMR': [True, True, True],
 'BVTK_NT_ImageToImageStencil': [True, True],
 'BVTK_NT_ImageToPoints': [],
 'BVTK_NT_ImageToPolyDataFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageToStructuredGrid': [],
 'BVTK_NT_ImageToStructuredPoints': [],
 'BVTK_NT_ImageTranslateExtent': [True],
 'BVTK_NT_ImageVariance3D': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageWeightedSum': [True, True, True, True, True, True, True],
 'BVTK_NT_ImageWrapPad': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ImageWriter': [True, True, True, True],
 'BVTK_NT_ImageYIQToRGB': [True, True, True, True, True, True, True],
 'BVTK_NT_ImplicitBoolean': [True],
 'BVTK_NT_ImplicitDataSet': [True, True],
 'BVTK_NT_ImplicitFunctionToImageStencil': [True, True, True, True],
 'BVTK_NT_ImplicitHalo': [True, True, True],
 'BVTK_NT_ImplicitModeller': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ImplicitPolyDataDistance': [True, True, True, True],
 'BVTK_NT_ImplicitSelectionLoop': [True, True],
 'BVTK_NT_ImplicitSum': [True],
 'BVTK_NT_ImplicitTextureCoords': [True],
 'BVTK_NT_ImplicitVolume': [True, True],
 'BVTK_NT_ImplicitWindowFunction': [True, True],
 'BVTK_NT_InterpolateDataSetAttributes': [True],
 'BVTK_NT_IntersectionPolyDataFilter': [True, True, True, True, True, True, True],
 'BVTK_NT_ISIReader': [True, True, True],
 'BVTK_NT_IterativeClosestPointTransform': [True, True, True, True, True, True],
 'BVTK_NT_IVWriter': [True],
 'BVTK_NT_JavaScriptDataWriter': [True, True, True],
 'BVTK_NT_JPEGReader': [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False],
 'BVTK_NT_JPEGWriter': [True, True, True, True, True, True, True],
 'BVTK_NT_JSONImageWriter': [True, True, True],
 'BVTK_NT_KdTreeSelector': [True, True, True, True, True],
 'BVTK_NT_KMeansStatistics': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_LabelHierarchyAlgorithm': [],
 'BVTK_NT_LabelSizeCalculator': [True, True],
 'BVTK_NT_LagrangianParticleTracker': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_LandmarkTransform': [True],
 'BVTK_NT_LassoStencilSource': [True, True, True, True, True],
 'BVTK_NT_LevelIdScalars': [],
 'BVTK_NT_LinearExtrusionFilter': [True, True, True, True, True],
 'BVTK_NT_LinearSelector': [True, True, True, True, True],
 'BVTK_NT_LinearSubdivisionFilter': [True, True],
 'BVTK_NT_LinearToQuadraticCellsFilter': [],
 'BVTK_NT_LineSource': [True, True, True],
 'BVTK_NT_LinkEdgels': [True, True, True],
 'BVTK_NT_LoopBooleanPolyDataFilter': [True, True, True],
 'BVTK_NT_LoopSubdivisionFilter': [True, True],
 'BVTK_NT_LSDynaReader': [True, True, True, True, True, True, True, True],
 'BVTK_NT_MapArrayValues': [True, True, True, True, True, True],
 'BVTK_NT_MarchingContourFilter': [True, True, True, True],
 'BVTK_NT_MarchingCubes': [True, True, True, True, True],
 'BVTK_NT_MarchingSquares': [True, True],
 'BVTK_NT_MaskFields': [],
 'BVTK_NT_MaskPoints': [True, True, True, True, True, True, True, True],
 'BVTK_NT_MaskPointsFilter': [True, True, True],
 'BVTK_NT_MaskPolyData': [True, True],
 'BVTK_NT_MatricizeArray': [True],
 'BVTK_NT_MatrixMathFilter': [True],
 'BVTK_NT_MatrixToHomogeneousTransform': [],
 'BVTK_NT_MatrixToLinearTransform': [],
 'BVTK_NT_MCubesReader': [True, True, True, True, True, True, True],
 'BVTK_NT_MCubesWriter': [True, True],
 'BVTK_NT_MedicalImageReader2': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_MemoryLimitImageDataStreamer': [True, True],
 'BVTK_NT_MergeDataObjectFilter': [True],
 'BVTK_NT_MergeFields': [True],
 'BVTK_NT_MergeFilter': [],
 'BVTK_NT_MeshQuality': [True, True, True, True, True, True, True, True],
 'BVTK_NT_MetaImageReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_MetaImageWriter': [True, True, True, True, True, True],
 'BVTK_NT_MFIXReader': [True, True, True],
 'BVTK_NT_MINCImageReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_MINCImageWriter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_MNIObjectReader': [True],
 'BVTK_NT_MNIObjectWriter': [True, True],
 'BVTK_NT_MNITagPointReader': [True],
 'BVTK_NT_MNITagPointWriter': [True, True],
 'BVTK_NT_MNITransformReader': [True],
 'BVTK_NT_MNITransformWriter': [True, True],
 'BVTK_NT_MoleculeAlgorithm': [],
 'BVTK_NT_MoleculeToAtomBallFilter': [True, True, True],
 'BVTK_NT_MoleculeToBondStickFilter': [],
 'BVTK_NT_MPASReader': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_MRCReader': [True],
 'BVTK_NT_MultiBlockDataGroupFilter': [],
 'BVTK_NT_MultiBlockDataSetAlgorithm': [],
 'BVTK_NT_MultiBlockFromTimeSeriesFilter': [],
 'BVTK_NT_MultiBlockMergeFilter': [],
 'BVTK_NT_MultiBlockPLOT3DReader': [False, False, False, False, False, False, False, False, False, False, False, False, True, False, True, False, True, True],
 'BVTK_NT_MultiCorrelativeStatistics': [True, True, True, True, True, True],
 'BVTK_NT_MultiNewickTreeReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_MultiThreshold': [],
 'BVTK_NT_NetCDFCFReader': [True, False, False, True, False, False],
 'BVTK_NT_NetCDFPOPReader': [True, True],
 'BVTK_NT_NetCDFReader': [True, True],
 'BVTK_NT_NewickTreeReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_NewickTreeWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_NIFTIImageReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_NIFTIImageWriter': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_NonOverlappingAMRAlgorithm': [],
 'BVTK_NT_NormalizeMatrixVectors': [True, True],
 'BVTK_NT_NrrdReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_OBBDicer': [True, True, True, True, True],
 'BVTK_NT_OBJReader': [True],
 'BVTK_NT_OggTheoraWriter': [True, True, True, True],
 'BVTK_NT_OpenFOAMReader': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_OrderStatistics': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_OutlineCornerFilter': [True],
 'BVTK_NT_OutlineCornerSource': [True, True, True, True, True],
 'BVTK_NT_OutlineFilter': [True],
 'BVTK_NT_OutlineSource': [True, True, True, True],
 'BVTK_NT_OverlappingAMRAlgorithm': [],
 'BVTK_NT_OverlappingAMRLevelIdScalars': [],
 'BVTK_NT_PairwiseExtractHistogram2D': [True, True, True, True, True, True, True],
 'BVTK_NT_ParallelCoordinatesHistogramRepresentation': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParallelCoordinatesRepresentation': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricBohemianDome': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricBour': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricBoy': [False, False, True, True, True, True, True, False, False, False, False, False, False, False, True],
 'BVTK_NT_ParametricCatalanMinimal': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricConicSpiral': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricCrossCap': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricDini': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricEllipsoid': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricEnneper': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricFigure8Klein': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricFunctionSource': [True, True, True, True, True, True],
 'BVTK_NT_ParametricHenneberg': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricKlein': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricKuen': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricMobius': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricPluckerConoid': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricPseudosphere': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricRandomHills': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricRoman': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricSpline': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricSuperEllipsoid': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricSuperToroid': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParametricTorus': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParticlePathFilter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_ParticleReader': [True, True, True, True, True],
 'BVTK_NT_ParticleTracer': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PassArrays': [True, True],
 'BVTK_NT_PassInputTypeAlgorithm': [],
 'BVTK_NT_PassThrough': [True, True],
 'BVTK_NT_PassThroughFilter': [],
 'BVTK_NT_PCAAnalysisFilter': [],
 'BVTK_NT_PCACurvatureEstimation': [True],
 'BVTK_NT_PCANormalEstimation': [True, True, True, True],
 'BVTK_NT_PCAStatistics': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PCellDataToPointData': [True, True, True],
 'BVTK_NT_PChacoReader': [True, True, True, True, True],
 'BVTK_NT_PComputeHistogram2DOutliers': [True],
 'BVTK_NT_PDataSetReader': [True],
 'BVTK_NT_PDataSetWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PDBReader': [True, True, True],
 'BVTK_NT_PerlinNoise': [True, True, True],
 'BVTK_NT_PerspectiveTransform': [],
 'BVTK_NT_PExtractArraysOverTime': [True],
 'BVTK_NT_PExtractHistogram2D': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PhyloXMLTreeReader': [True, True, True, True],
 'BVTK_NT_PhyloXMLTreeWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PieceRequestFilter': [True, True],
 'BVTK_NT_PieceScalars': [True],
 'BVTK_NT_PiecewiseFunctionAlgorithm': [],
 'BVTK_NT_PiecewiseFunctionShiftScale': [True, True, True, True],
 'BVTK_NT_PImageWriter': [True, True, True, True, True],
 'BVTK_NT_Plane': [True, True],
 'BVTK_NT_PlaneCutter': [True, True, True, True, True],
 'BVTK_NT_Planes': [],
 'BVTK_NT_PlanesIntersection': [],
 'BVTK_NT_PlaneSource': [True, True, True, True, True, True, True],
 'BVTK_NT_PlatonicSolidSource': [True],
 'BVTK_NT_PLinearExtrusionFilter': [True, True, True, True, True, True],
 'BVTK_NT_Plot3DMetaReader': [True],
 'BVTK_NT_PLYReader': [True],
 'BVTK_NT_PLYWriter': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PMaskPoints': [True, True, True, True, True, True, True, True],
 'BVTK_NT_PNGReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PNGWriter': [True, True, True, True, True, True],
 'BVTK_NT_PNMReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PNMWriter': [True, True, True, True],
 'BVTK_NT_PointConnectivityFilter': [],
 'BVTK_NT_PointDataToCellData': [True, True],
 'BVTK_NT_PointDensityFilter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PointInterpolator': [True, True, True, True, True, True, True],
 'BVTK_NT_PointInterpolator2D': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PointLoad': [True, True, True, True, True],
 'BVTK_NT_PointOccupancyFilter': [True, True, True, True],
 'BVTK_NT_PointSetAlgorithm': [],
 'BVTK_NT_PointSetToLabelHierarchy': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PointSource': [True, True, True, True],
 'BVTK_NT_PolyDataAlgorithm': [],
 'BVTK_NT_PolyDataConnectivityFilter': [True, True, True, True, True, True, True],
 'BVTK_NT_PolyDataNormals': [False, False, False, False, False, False, False, False],
 'BVTK_NT_PolyDataPointSampler': [True, True, True, True, True],
 'BVTK_NT_PolyDataReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PolyDataSilhouette': [True, True, True, True, True, True, True],
 'BVTK_NT_PolyDataStreamer': [True, True],
 'BVTK_NT_PolyDataToImageStencil': [True, True, True, True],
 'BVTK_NT_PolyDataToReebGraphFilter': [True],
 'BVTK_NT_PolyDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PolyLineSource': [True, True],
 'BVTK_NT_PolyPlane': [],
 'BVTK_NT_POpenFOAMReader': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PostScriptWriter': [True, True, True, True],
 'BVTK_NT_POutlineCornerFilter': [True],
 'BVTK_NT_POutlineFilter': [],
 'BVTK_NT_PPairwiseExtractHistogram2D': [True, True, True, True, True, True, True],
 'BVTK_NT_PPolyDataNormals': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PProbeFilter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PProjectSphereFilter': [True, True, True],
 'BVTK_NT_PReflectionFilter': [True, True, True, True],
 'BVTK_NT_PResampleFilter': [True, True, True],
 'BVTK_NT_ProbeFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ProbePolyhedron': [True, True],
 'BVTK_NT_ProbeSelectedLocations': [True],
 'BVTK_NT_ProcessIdScalars': [True],
 'BVTK_NT_ProcrustesAlignmentFilter': [True],
 'BVTK_NT_ProgrammableAttributeDataFilter': [],
 'BVTK_NT_ProgrammableDataObjectSource': [],
 'BVTK_NT_ProgrammableFilter': [True],
 'BVTK_NT_ProgrammableGlyphFilter': [True],
 'BVTK_NT_ProgrammableSource': [],
 'BVTK_NT_ProjectedTerrainPath': [True, True, True, True],
 'BVTK_NT_ProjectedTexture': [True, True, True, True, True, True, True, True],
 'BVTK_NT_ProjectSphereFilter': [True, True, True],
 'BVTK_NT_ProStarReader': [True, True],
 'BVTK_NT_ProteinRibbonFilter': [True, True, True, True, True],
 'BVTK_NT_PSLACReader': [True, True, True, True],
 'BVTK_NT_PSphereSource': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_PTSReader': [True, True, True, True, True, True, True, True],
 'BVTK_NT_PYoungsMaterialInterface': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_QuadraturePointInterpolator': [],
 'BVTK_NT_QuadraturePointsGenerator': [],
 'BVTK_NT_QuadratureSchemeDictionaryGenerator': [],
 'BVTK_NT_Quadric': [True],
 'BVTK_NT_QuadricClustering': [True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_QuadricDecimation': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_QuadRotationalExtrusionFilter': [True, True, True, True, True, True],
 'BVTK_NT_QuantizePolyDataPoints': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_RadiusOutlierRemoval': [True, True, True, True],
 'BVTK_NT_RandomAttributeGenerator': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_RearrangeFields': [],
 'BVTK_NT_RectangularButtonSource': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_RectilinearGridAlgorithm': [],
 'BVTK_NT_RectilinearGridClip': [True],
 'BVTK_NT_RectilinearGridGeometryFilter': [True],
 'BVTK_NT_RectilinearGridOutlineFilter': [],
 'BVTK_NT_RectilinearGridPartitioner': [True, True, True],
 'BVTK_NT_RectilinearGridReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_RectilinearGridToPointSet': [],
 'BVTK_NT_RectilinearGridToTetrahedra': [True, True],
 'BVTK_NT_RectilinearGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_RectilinearSynchronizedTemplates': [True, True, True, True, True, True],
 'BVTK_NT_RecursiveDividingCubes': [True, True, True],
 'BVTK_NT_ReflectionFilter': [True, True, True, True],
 'BVTK_NT_RegularPolygonSource': [True, True, True, True, True, True],
 'BVTK_NT_RemoveGhosts': [],
 'BVTK_NT_ResampleToImage': [True, True, True],
 'BVTK_NT_ResampleWithDataSet': [True, True, True, True, True, True, True],
 'BVTK_NT_ResliceCursorPolyDataAlgorithm': [True, True],
 'BVTK_NT_ReverseSense': [True, True],
 'BVTK_NT_RibbonFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_RISReader': [True, True, True],
 'BVTK_NT_ROIStencilSource': [True, True, True, True, True],
 'BVTK_NT_RotationalExtrusionFilter': [True, True, True, True, True],
 'BVTK_NT_RotationFilter': [True, True, True, True, True],
 'BVTK_NT_RowQueryToTable': [],
 'BVTK_NT_RTAnalyticSource': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_RTXMLPolyDataReader': [True, True, True, True],
 'BVTK_NT_RuledSurfaceFilter': [True, True, True, True, True, True, True, True],
 'BVTK_NT_RungeKutta2': [],
 'BVTK_NT_RungeKutta4': [],
 'BVTK_NT_RungeKutta45': [],
 'BVTK_NT_SampleFunction': [True, True, True, True, True, True, True, True],
 'BVTK_NT_SampleImplicitFunctionFilter': [True, True, True],
 'BVTK_NT_SectorSource': [True, True, True, True, True, True, True],
 'BVTK_NT_SelectEnclosedPoints': [True, True, True],
 'BVTK_NT_SelectionAlgorithm': [],
 'BVTK_NT_SelectionSource': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SelectPolyData': [True, True, True, True, True],
 'BVTK_NT_ShepardMethod': [True, True, True, True, True],
 'BVTK_NT_ShrinkFilter': [True],
 'BVTK_NT_ShrinkPolyData': [True],
 'BVTK_NT_SignedDistance': [True, True, True],
 'BVTK_NT_SimpleBondPerceiver': [True],
 'BVTK_NT_SimpleElevationFilter': [True],
 'BVTK_NT_SimpleImageFilterExample': [],
 'BVTK_NT_SimplePointsReader': [True],
 'BVTK_NT_SimplePointsWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SLACParticleReader': [True],
 'BVTK_NT_SLACReader': [True, True, True, True],
 'BVTK_NT_SLCReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SmoothPolyDataFilter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SMPContourGrid': [True, True, True, True, True, True],
 'BVTK_NT_SpatialRepresentationFilter': [True],
 'BVTK_NT_Sphere': [True, True],
 'BVTK_NT_SpherePuzzle': [],
 'BVTK_NT_SpherePuzzleArrows': [True],
 'BVTK_NT_SphereSource': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SphereTreeFilter': [True, True, True, True, True, True],
 'BVTK_NT_SphericalTransform': [True, True],
 'BVTK_NT_SPHInterpolator': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SplineFilter': [True, True, True, True, True, True],
 'BVTK_NT_SplitByCellScalarFilter': [True],
 'BVTK_NT_SplitColumnComponents': [True, True],
 'BVTK_NT_SplitField': [],
 'BVTK_NT_SQLDatabaseTableSource': [True, True, True, True],
 'BVTK_NT_SQLiteToTableReader': [],
 'BVTK_NT_StatisticalOutlierRemoval': [True, True, True, True, True, True],
 'BVTK_NT_STLReader': [True, True, True],
 'BVTK_NT_STLWriter': [True, True, True],
 'BVTK_NT_StrahlerMetric': [True],
 'BVTK_NT_StreaklineFilter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_StreamingStatistics': [],
 'BVTK_NT_StreamTracer': [False, True, False, False, True, False, False, False, True, True, False, False, False, False],
 'BVTK_NT_Stripper': [True, True, True, True, True],
 'BVTK_NT_StructuredGridAlgorithm': [],
 'BVTK_NT_StructuredGridAppend': [],
 'BVTK_NT_StructuredGridClip': [True],
 'BVTK_NT_StructuredGridGeometryFilter': [True],
 'BVTK_NT_StructuredGridGhostDataGenerator': [True],
 'BVTK_NT_StructuredGridOutlineFilter': [],
 'BVTK_NT_StructuredGridPartitioner': [True, True, True],
 'BVTK_NT_StructuredGridReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_StructuredGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_StructuredPointsReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_StructuredPointsWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SubdivideTetra': [],
 'BVTK_NT_SubPixelPositionEdgels': [True, True],
 'BVTK_NT_Superquadric': [True, True, True, True, True, True, True],
 'BVTK_NT_SuperquadricSource': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_SurfaceReconstructionFilter': [True, True],
 'BVTK_NT_SynchronizedTemplates2D': [True, True, True],
 'BVTK_NT_SynchronizedTemplatesCutter3D': [True, True, True, True, True, True, True],
 'BVTK_NT_SynchronizeTimeFilter': [True],
 'BVTK_NT_TableAlgorithm': [],
 'BVTK_NT_TableBasedClipDataSet': [True, True, True, True, True, True],
 'BVTK_NT_TableFFT': [],
 'BVTK_NT_TableReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TableToPolyData': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TableToSQLiteWriter': [],
 'BVTK_NT_TableToStructuredGrid': [True, True, True, True, True, True],
 'BVTK_NT_TableWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TecplotReader': [],
 'BVTK_NT_TecplotTableReader': [True, True, True, True, True, True, True, True],
 'BVTK_NT_TemporalArrayOperatorFilter': [True, True, True, True],
 'BVTK_NT_TemporalDataSetCache': [True],
 'BVTK_NT_TemporalFractal': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TemporalInterpolator': [False, False, True],
 'BVTK_NT_TemporalPathLineFilter': [True, True, True, True, True],
 'BVTK_NT_TemporalShiftScale': [True, True, True, True, True, True],
 'BVTK_NT_TemporalSnapToTimeStep': [True],
 'BVTK_NT_TemporalStatistics': [True, True, True, True],
 'BVTK_NT_TemporalStreamTracer': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TensorGlyph': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TessellatedBoxSource': [True, True, True, True],
 'BVTK_NT_TessellatorFilter': [True, True, True, True],
 'BVTK_NT_TextSource': [True, True, True, True],
 'BVTK_NT_TexturedSphereSource': [True, True, True, True, True],
 'BVTK_NT_TextureMapToCylinder': [True, True, True, True],
 'BVTK_NT_TextureMapToPlane': [True, True, True, True, True, True, True],
 'BVTK_NT_TextureMapToSphere': [True, True, True],
 'BVTK_NT_ThinPlateSplineTransform': [True, True, True, True],
 'BVTK_NT_Threshold': [True, True, True, True, True, True],
 'BVTK_NT_ThresholdPoints': [True, True],
 'BVTK_NT_ThresholdTextureCoords': [True, True, True],
 'BVTK_NT_TIFFReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TIFFWriter': [True, True, True, True, True],
 'BVTK_NT_TimeSourceExample': [True, True, True, True],
 'BVTK_NT_Transform': [],
 'BVTK_NT_TransformCoordinateSystems': [True, True],
 'BVTK_NT_TransformFilter': [],
 'BVTK_NT_TransformPolyDataFilter': [],
 'BVTK_NT_TransformTextureCoords': [True, True, True, True, True, True],
 'BVTK_NT_TransformToGrid': [True, True, True, True],
 'BVTK_NT_TransmitImageDataPiece': [True],
 'BVTK_NT_TransmitPolyDataPiece': [True],
 'BVTK_NT_TransmitRectilinearGridPiece': [True],
 'BVTK_NT_TransmitStructuredDataPiece': [True],
 'BVTK_NT_TransmitStructuredGridPiece': [True],
 'BVTK_NT_TransmitUnstructuredGridPiece': [True],
 'BVTK_NT_TransposeTable': [True, True, True],
 'BVTK_NT_TreeAlgorithm': [],
 'BVTK_NT_TreeReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TreeWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_TriangleFilter': [True, True],
 'BVTK_NT_TriangleMeshPointNormals': [],
 'BVTK_NT_TriangularTCoords': [],
 'BVTK_NT_TriangularTexture': [True, True, True, True],
 'BVTK_NT_TrivialProducer': [],
 'BVTK_NT_TubeFilter': [True, False, False, True, False, False, True, False, False, False, False, True],
 'BVTK_NT_TulipReader': [True],
 'BVTK_NT_UncertaintyTubeFilter': [True],
 'BVTK_NT_UndirectedGraphAlgorithm': [],
 'BVTK_NT_UniformGridAMRAlgorithm': [],
 'BVTK_NT_UniformGridGhostDataGenerator': [True],
 'BVTK_NT_UniformGridPartitioner': [True, True, True],
 'BVTK_NT_UnsignedDistance': [True, True, True, True, True, True, True, True],
 'BVTK_NT_UnstructuredGridAlgorithm': [],
 'BVTK_NT_UnstructuredGridBaseAlgorithm': [],
 'BVTK_NT_UnstructuredGridGeometryFilter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_UnstructuredGridQuadricDecimation': [True, True, True, True, True, True, True, True],
 'BVTK_NT_UnstructuredGridReader': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_UnstructuredGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_VASPAnimationReader': [True],
 'BVTK_NT_VASPTessellationReader': [True],
 'BVTK_NT_VectorDot': [True, True],
 'BVTK_NT_VectorNorm': [True, True],
 'BVTK_NT_VectorText': [True],
 'BVTK_NT_VertexGlyphFilter': [],
 'BVTK_NT_VideoSource': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_Volume16Reader': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_VolumeContourSpectrumFilter': [True, True, True],
 'BVTK_NT_VolumeOfRevolutionFilter': [True, True, True, True],
 'BVTK_NT_VolumeRayCastSpaceLeapingImageFilter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_VoxelContoursToSurfaceFilter': [True, True],
 'BVTK_NT_VoxelGrid': [True, True, True, True],
 'BVTK_NT_VoxelModeller': [True, True, True, True, True, True],
 'BVTK_NT_WarpLens': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_WarpScalar': [False, True, False, False],
 'BVTK_NT_WarpTo': [True, True, True],
 'BVTK_NT_WarpVector': [True],
 'BVTK_NT_WeightedTransformFilter': [True, True, True, True, True, True],
 'BVTK_NT_WindBladeReader': [True, True],
 'BVTK_NT_WindowedSincPolyDataFilter': [True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_WindowToImageFilter': [True, True, True, True, True, True],
 'BVTK_NT_XGMLReader': [True],
 'BVTK_NT_XMLDataObjectWriter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLDataSetWriter': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLGenericDataObjectReader': [True, True, True, True],
 'BVTK_NT_XMLHierarchicalBoxDataReader': [True, True, True, True, True, True],
 'BVTK_NT_XMLHierarchicalBoxDataWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLHierarchicalDataReader': [True, True, True, True, True],
 'BVTK_NT_XMLImageDataReader': [True, True, True, True, True],
 'BVTK_NT_XMLImageDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLMultiBlockDataReader': [True, True, True, True, True],
 'BVTK_NT_XMLMultiBlockDataWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLMultiGroupDataReader': [True, True, True, True, True],
 'BVTK_NT_XMLPDataSetWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPHierarchicalBoxDataWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPImageDataReader': [True, True, True, True],
 'BVTK_NT_XMLPImageDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPMultiBlockDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPolyDataReader': [True, True, True, True],
 'BVTK_NT_XMLPolyDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPPolyDataReader': [True, True, True, True],
 'BVTK_NT_XMLPPolyDataWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPRectilinearGridReader': [True, True, True, True],
 'BVTK_NT_XMLPRectilinearGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPStructuredGridReader': [True, True, True, True],
 'BVTK_NT_XMLPStructuredGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPTableReader': [True, True, True, True],
 'BVTK_NT_XMLPTableWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPUniformGridAMRWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLPUnstructuredGridReader': [True, True, True, True],
 'BVTK_NT_XMLPUnstructuredGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLRectilinearGridReader': [True, True, True, True, True],
 'BVTK_NT_XMLRectilinearGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLStructuredGridReader': [True, True, True, True, True],
 'BVTK_NT_XMLStructuredGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLTableReader': [True, True, True, True],
 'BVTK_NT_XMLTableWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLTreeReader': [True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLUniformGridAMRReader': [True, True, True, True, True, True],
 'BVTK_NT_XMLUniformGridAMRWriter': [True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XMLUnstructuredGridReader': [True, True, True, True],
 'BVTK_NT_XMLUnstructuredGridWriter': [True, True, True, True, True, True, True, True, True, True, True, True],
 'BVTK_NT_XYZMolReader': [True, True, True, True],
 'BVTK_NT_XYZMolReader2': [True],
 'BVTK_NT_YoungsMaterialInterface': [True, True, True, True, True, True, True, True, True],
}
